[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[scheduled]]
  name = "sync-printful-merch-nightly"
  cron = "0 3 * * *" # Runs every day at 3am UTC
  function = "sync-printful-merch"

[functions."update-printful-cache"]
  schedule = "0 4 * * *" # Run daily at 4 AM UTC
